### ISSUE TITLE
Extension causes extensionhost to crash

### ISSUE THREAD

**Issue by extide** [stephen-riley/regexworkbench#15]
Issue Type: <b>Bug</b>

This extension is seemingly causing my  extensionhost to crash. See attached information and feel free to reach out if you need more information.

Extension version: 2.0.5
VS Code version: Code - Insiders 1.55.0-insider (111a6cec70f9562cdd31a5fd8cdea4b3a9b7bd82, 2021-03-18T05:14:49.087Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.75GB (27.67GB free)|
|Process Argv|--enable-proposed-api VisualStudioExptTeam.vscodeintellicode --enable-proposed-api ms-kubernetes-tools.vscode-aks-tools --enable-proposed-api AzurePolicy.azurepolicyextension --enable-proposed-api ZainChen.json --enable-proposed-api ms-azuretools.vscode-azurestaticwebapps --enable-proposed-api msazurermtools.azurerm-vscode-tools --enable-proposed-api AzurePolicy.azurepolicyextension --crash-reporter-id 1241d4b6-7524-4c9b-829d-6d54059c7e99|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
vscoresta800cf:30265948
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by extide** [comment]
I was finally able to capture a log -- sorry about the delay. Unfortunately it does appear there are several issues affecting me at the moment, so I will try and resolve some of these and post some more updated logs in the future.

[20210324T181353.zip](https://github.com/stephen-riley/regexworkbench/files/6201478/20210324T181353.zip)

Extension Host
log.ts:296   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, GrapeCity.gc-excelviewer, mechatroner.rainbow-csv, ms-vscode-remote.remote-ssh-edit-nightly, DotJoshJohnson.xml, pflannery.vscode-versionlens, tintoy.msbuild-project-tools, tomsaunders.vscode-workspace-explorer, vscode.debug-auto-launch, vscode.git, 2gua.rainbow-brackets, samverschueren.yo, cweijan.vscode-mysql-client2, donjayamanne.githistory, dqisme.sync-scroll, ecmel.vscode-html-css, redhat.vscode-yaml, fernandoescolar.vscode-solution-explorer, fivepointseven.node-version, HCLTechnologies.hclappscancodesweep, HookyQR.beautify, HookyQR.minify, ionutvmi.reg, JHeilingbrunner.vscode-gnupg-tool, jock.svg, marco-pierobon.git-graphy, mhutchie.git-graph, vscode.sql, mindaro-dev.file-downloader, ms-vscode.azure-account, neilbarkhina.gitdownloadazurerepos, PKief.material-icon-theme, rexebin.f12-open-file, RoscoP.ActiveFileInStatusBar, slevesque.vscode-multiclip, spmeesseman.vscode-taskexplorer, stephen-riley.regexworkbench, stylelint.vscode-stylelint, TabNine.tabnine-vscode, msjsdiag.debugger-for-edge, msjsdiag.debugger-for-chrome, treetrum.statusbar-format-on-save, VisualStudioOnlineApplicationInsights.application-insights, vscode-icons-team.vscode-icons, wraith13.windows-terminal, xshrim.txt-syntax, zhuangtongfa.material-theme, Zignd.html-css-class-completion, vscode.emmet, vscode.merge-conflict, ms-vscode-remote.remote-wsl-recommender, vscode.testing-editor-contributions, codespaces-contrib.codeswing, eamodio.gitlens, esbenp.prettier-vscode, ms-vscode-remote.remote-containers, ms-vscode-remote.remote-wsl, vscode.configuration-editing, vscode.json-language-features, vscode.typescript-language-features, ms-dotnettools.vscode-dotnet-runtime, ms-vscode.js-debug, vscode.github, azuresdkteam.azurenodeessentials, fbaligand.vscode-logstash-editor, ms-mssql.mssql, ms-kubernetes-tools.vscode-kubernetes-tools, ms-vscode-deploy-azure.azure-deploy, onlyutkarsh.git-config-user-profiles, Summer.azure-event-hub-explorer, TeamsDevApp.ms-teams-vscode-extension, msazurermtools.azurerm-vscode-tools, vscode.github-authentication, Microsoft.admin-tool-ext-win, Microsoft.agent, mindaro.mindaro


localProcessExtensionHost.ts:272 Extension Host
localProcessExtensionHost.ts:273 c:\Users\jamfry.MDM\.vscode-insiders\extensions\stephen-riley.regexworkbench-2.0.5\node_modules\@stephen-riley\pcre2-wasm\dist\libpcre2.js:95
   throw ex;
   ^
Error: ECONNRESET: connection reset by peer, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
Emitted 'error' event on FSWatcher instance at:
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:133:12) {
  errno: -4077,
  syscall: 'watch',
  code: 'ECONNRESET',
  filename: null
}

**Comment by ThaDaVos** [comment]
Same happening for me - after removing this extension it stopped crashing...

**Comment by MinekPo1** [comment]
I also experienced this.

**Comment by MehbubRashid** [comment]
same issue.
